# Generated by Django 2.2.4 on 2019-08-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190810_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.')], default='Mr', max_length=3),
        ),
    ]
