# Generated by Django 2.2.4 on 2019-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_donor_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='title',
            field=models.CharField(choices=[('DR', 'Dr.'), ('DR_MED', 'Dr. med.'), ('DR_MED_DENT', 'Dr. med. dent.'), ('DR_PHARM', 'Dr. pharm.'), ('DR_RER_HUM', 'Dr. rer. hum.'), ('PROF', 'Prof.'), ('PROF_DR', 'Prof. Dr.')], default='DR', max_length=15),
        ),
    ]
