# Generated by Django 2.2.4 on 2019-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_donor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
