# Generated by Django 2.2 on 2019-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_donor_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
