# Generated by Django 2.2.4 on 2019-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190812_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
