# Generated by Django 2.2.4 on 2019-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_donor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='houseno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
