# Generated by Django 2.2.4 on 2019-08-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_donor_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.')], default='Mr', max_length=3)),
                ('title', models.CharField(choices=[('DR', 'Dr.'), ('DR_MED', 'Dr. med.'), ('DR_MED_DENT', 'Dr. med. dent.'), ('DR_PHARM', 'Dr. pharm.'), ('DR_RER_HUM', 'Dr. rer. hum.'), ('PROF', 'Prof.'), ('PROF_DR', 'Prof. Dr.')], default='DR', max_length=15)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='title',
        ),
        migrations.AddField(
            model_name='donor',
            name='personal_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PersonalInformation'),
        ),
    ]
