# Generated by Django 2.2.4 on 2019-08-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20190814_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='description',
        ),
    ]
